### ISSUE TITLE
TOML files shouldn't lose the license header

### ISSUE THREAD

**Issue by flodolo** [mozilla-l10n/firefox-l10n-source#13]
Noticed in https://github.com/mozilla-l10n/firefox-l10n-source/pull/9

We shouldn't lose the MPL2 license header.

**Comment by eemeli** [comment]
The header is not needed in the files, because the config or localization files in this repository are not in their Source Code Form, as defined in [the license](https://www.mozilla.org/en-US/MPL/2.0/):
     
> **1.13. “Source Code Form”**
> means the form of the work preferred for making modifications.

Therefore, they are:

> **1.6. “Executable Form”**
> means any form of the work other than Source Code Form.

Therefore, the guidance we must follow is in **3.2. Distribution of Executable Form** rather than **3.1. Distribution of Source Form**.

We should mention this explicitly in the README, and as per 3.2.a let people know where they should look for the sources.
